### ISSUE TITLE
Two-hand to show expose no longer works

### ISSUE THREAD

**Issue by mcongrove** [hagino3000/KinectJesture#1]
The two-hand gesture to show all applications, as shown in the demonstration video, does not appear to be working in the current build.

**Comment by hagino3000** [comment]
Currently this program fires keycode101(F9). You set keyboard shortcut F9 to [Show all window] then it will works well.

**Comment by mcongrove** [comment]
Sorry about that; another program was overriding the key.

I quickly parsed through the code but didn't see where this was mapped; can you point me in the right direction?

**Comment by hagino3000** [comment]
Line 180 to 183 at src/handjesture.cpp

**Comment by mcongrove** [comment]
Thanks very much :) Great code, by the way!
